package org.leap;

import com.sforce.soap.partner.DescribeSObjectResult;
import com.sforce.soap.partner.Field;
import com.sforce.ws.ConnectionException;

public class SFieldsTask extends LeapTask {
	
	public void execute() {
		this.genSFieldClass();
	}
	
	private void genSFieldClass(){
		System.out.println("// Auto generated by Kaizen framework. Do not modify this file. All changes will be overwritten in next build.");
		System.out.println("public with sharing class SObjectFields{");
		for (int i = 0; i < this.sObjects().length; i++) {
			String fieldName = "ALL_" + this.sObjects()[i].getName().replace(this.namespace, "").replace("__c", "").toUpperCase() + "_FIELDS";
			String output = "\tpublic static final String " + fieldName + " = '";
			
			DescribeSObjectResult describeSObjectResult = null;
			try {
				describeSObjectResult = this.salesforceConnection().getPartnerConnection().describeSObject(this.sObjects()[i].getName());
			} catch (ConnectionException e) {
				e.printStackTrace();
			}
			
			Field[] fields = describeSObjectResult.getFields();
			
			for (int j = 0; j < fields.length; j++) {
				Field field = fields[j];
				output += field.getName() + ",";
			}
			output += "';";
			output = output.replace(",'", "'");
			System.out.println(output);
		}
		System.out.println("}");
	}
}
